### ISSUE TITLE
Create an architecture diagram show how the FE, App BE, & ML BE communicate with one another

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v27-bears-team-06#48]
**__Task Description__**
Create an architecture diagram show how the FE, App BE, & ML BE communicate with one another

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by fancyaction** [comment]
https://drive.google.com/drive/folders/1VgBhTgYgymTMCGlhxVWvzmvYvzeh6-GO
